### ISSUE TITLE
[bug] asNumber and asBoolean doesn't works

### ISSUE THREAD

**Issue by xabufr** [christav/typed-config#1]
Provided asNumber returns always `NaN`.
After investigating using this function solves the problem:
```typescript
function asNumber(obj: any, name: string, val: any) {
    return +val;
}
```
This is because parameters are not in the right order here: https://github.com/christav/typed-config/blob/master/src/load-configuration.ts#L52

**Comment by christav** [comment]
finally looked at this after who knows how long. This has been fixed for a while.
